### ISSUE TITLE
Options when submitting territories?

### ISSUE THREAD

**Issue by wtokumaru** [chronoscio/backend#45]
Right now the back end prevents you from saving if you try to point a Territory to a Nation which already has one. Is this what we want?

Tangentially related: Trying to submit a Territory without specifying a nation causes a django error when you click save instead of blocking the save like any other invalid input does.

**Comment by whirish** [comment]
I'm unable to reproduce your first issue, perhaps you're running into the "Another territory of this PoliticalEntity exists during this timeframe" error when you have multiple territories for the same nation that exist within the same time period, which is intentional.

Good catch on the second though, I'm going to log it in a separate ticket and submit a fix.

**Comment by wtokumaru** [comment]
The first one sounds like it does what it is supposed to do so closing issue.
